In [1]:
#Importing necessary libraries
import pandas as pd
import numpy as np

In [12]:
# Read the csv file and save it as a Pandas DataFrame
df_Rohit = pd.read_csv("D:/knowledge/college docs/DSP/Project_1/New/Rohit_Final.csv")

In [13]:
df_Rohit.head()

Unnamed: 0                                         Commentary  Runs  \
0           2  Morne Morkel to Rohit, no run, stays in the cr...     0   
1           3  Morne Morkel to Rohit, 2 runs, <b>almost dragg...     2   
2           4  Rabada to Rohit, 1 run, good comeback from Rab...     1   
3           5  Rabada to Rohit, no run, Rohit must be cursing...     0   
4           6  Rabada to Rohit, no run, pacy back of a length...     0   

  Delivery_Length     Delivery_Line       Shot_Type Run/NoRun     Bowler_Type  \
0           Short    outside_stumps  Defensive_shot     norun  right arm fast   
1           Short  wicket_to_wicket            Edge       run  right arm fast   
2      GoodLength    outside_stumps        Late_Cut       run  right arm fast   
3       Full_toss    outside_stumps       Pull_hook     norun  right arm fast   
4           Short  wicket_to_wicket  Defensive_shot     norun  right arm fast   

    Bowler_Name  Avg_Ball_Speed ...   Beaten/NotBeaten  Home_Away  \
0  Morne Morkel           139.2 ...         not_beaten       away   
1  Morne Morkel           139.2 ...             beaten       away   
2        Rabada           138.3 ...             beaten       away   
3        Rabada           138.3 ...         not_beaten       away   
4        Rabada           138.3 ...         not_beaten       away   

  Good_Bad_Shot      Opponent    Stadium  Shot_Zone Delivery_Number Toss  \
0           bad  South Africa  Kingsmead    Unknown              29    0   
1           bad  South Africa  Kingsmead    FineLeg              28    0   
2          good  South Africa  Kingsmead      Point              27    0   
3           bad  South Africa  Kingsmead  Midwicket              26    0   
4           bad  South Africa  Kingsmead    Unknown              25    0   

  TossDecision  D/N  
0      Batting   DN  
1      Batting   DN  
2      Batting   DN  
3      Batting   DN  
4      Batting   DN  

[5 rows x 23 columns]

In [14]:
null_columns=df_Rohit.columns[df_Rohit.isnull().any()]
null_columns

Index(['Dismissal_Type'], dtype='object')

In [15]:
df_Rohit['Delivery_Length'].value_counts()

Short         817
Full          643
GoodLength    515
Unknown       177
Full_toss      40
Name: Delivery_Length, dtype: int64

In [16]:
df_Rohit['Delivery_Line'].value_counts()

outside_stumps      1004
wicket_to_wicket     949
Unknown              239
Name: Delivery_Line, dtype: int64

In [17]:
df_Rohit['Shot_Type'].value_counts()

Defensive_shot    461
Drive             395
Unknown           327
Pull_hook         261
Late_Cut          160
Cut               141
No_shot           139
Edge              110
Flick             105
Sweep              76
Glance             17
Name: Shot_Type, dtype: int64

In [18]:
df_Rohit['Shot_Zone'].value_counts()

Unknown      764
Cover        290
Point        236
LongOn       208
Midwicket    185
ThirdMan     164
LongOff      131
SquareLeg    124
FineLeg       90
Name: Shot_Zone, dtype: int64

In [19]:
df_Rohit['Bowler_Type'].value_counts()

right arm fast medium    620
right arm fast           435
right arm medium         243
right arm off break      232
left arm fast medium     211
left arm orthodox        201
left arm medium          128
right arm leg break       86
left arm chinaman         36
Name: Bowler_Type, dtype: int64

# Model 1

In [44]:
cols = ['Bowler_Type','Delivery_Length','Delivery_Line','Avg_Ball_Speed','Delivery_Number','Home_Away','Shot_Type']

x = df_Rohit[cols]
df_Rohit_Y = df_Rohit['Good_Bad_Shot']
Avg_Ball_Speed=df_Rohit['Avg_Ball_Speed']
Delivery_Number=df_Rohit['Delivery_Number']
#line_df = rohit['Delivery Line'].to_frame
dummy_bowler_type = pd.get_dummies(df_Rohit['Bowler_Type'])
dummy_home_away = pd.get_dummies(df_Rohit['Delivery_Length'])
dummy_line = pd.get_dummies(df_Rohit['Delivery_Line'])
dummy_length = pd.get_dummies(df_Rohit['Home_Away'])
dummy_shotype = pd.get_dummies(df_Rohit['Shot_Type'])
#dummy_line
df_Rohit_X = pd.concat([Avg_Ball_Speed,Delivery_Number,dummy_bowler_type,dummy_home_away,dummy_line,dummy_length,dummy_shotype],axis = 1)
df_Rohit_X.head()


Avg_Ball_Speed  Delivery_Number  left arm chinaman  left arm fast medium  \
0           139.2               29                  0                     0   
1           139.2               28                  0                     0   
2           138.3               27                  0                     0   
3           138.3               26                  0                     0   
4           138.3               25                  0                     0   

   left arm medium  left arm orthodox  right arm fast  right arm fast medium  \
0                0                  0               1                      0   
1                0                  0               1                      0   
2                0                  0               1                      0   
3                0                  0               1                      0   
4                0                  0               1                      0   

   right arm leg break  right arm medium   ...     Defensive_shot  Drive  \
0                    0                 0   ...                  1      0   
1                    0                 0   ...                  0      0   
2                    0                 0   ...                  0      0   
3                    0                 0   ...                  0      0   
4                    0                 0   ...                  1      0   

   Edge  Flick  Glance  Late_Cut  No_shot  Pull_hook  Sweep  Unknown  
0     0      0       0         0        0          0      0        0  
1     1      0       0         0        0          0      0        0  
2     0      0       0         1        0          0      0        0  
3     0      0       0         0        0          1      0        0  
4     0      0       0         0        0          0      0        0  

[5 rows x 32 columns]

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [46]:
x_train, x_test, y_train, y_test = train_test_split(df_Rohit_X, df_Rohit_Y, test_size=0.2,stratify=df_Rohit_Y, random_state=42)

In [47]:
df_Rohit_X.head()

Avg_Ball_Speed  Delivery_Number  left arm chinaman  left arm fast medium  \
0           139.2               29                  0                     0   
1           139.2               28                  0                     0   
2           138.3               27                  0                     0   
3           138.3               26                  0                     0   
4           138.3               25                  0                     0   

   left arm medium  left arm orthodox  right arm fast  right arm fast medium  \
0                0                  0               1                      0   
1                0                  0               1                      0   
2                0                  0               1                      0   
3                0                  0               1                      0   
4                0                  0               1                      0   

   right arm leg break  right arm medium   ...     Defensive_shot  Drive  \
0                    0                 0   ...                  1      0   
1                    0                 0   ...                  0      0   
2                    0                 0   ...                  0      0   
3                    0                 0   ...                  0      0   
4                    0                 0   ...                  1      0   

   Edge  Flick  Glance  Late_Cut  No_shot  Pull_hook  Sweep  Unknown  
0     0      0       0         0        0          0      0        0  
1     1      0       0         0        0          0      0        0  
2     0      0       0         1        0          0      0        0  
3     0      0       0         0        0          1      0        0  
4     0      0       0         0        0          0      0        0  

[5 rows x 32 columns]

In [48]:
from sklearn import tree

In [49]:
tree_model=tree.DecisionTreeClassifier(max_depth=4)
tree_model.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [50]:
dt_shot_pred=tree_model.predict(x_test)

In [51]:
print(accuracy_score(y_test,dt_shot_pred))

0.824601366743


In [52]:
print(confusion_matrix(y_test,dt_shot_pred))
print(classification_report(y_test,dt_shot_pred))

[[283  20]
 [ 57  79]]
             precision    recall  f1-score   support

        bad       0.83      0.93      0.88       303
       good       0.80      0.58      0.67       136

avg / total       0.82      0.82      0.82       439



# Model 2

In [130]:
#cols = ['Bowler_Type','Delivery_Length','Delivery_Line','Home_Away','Shot_Type']

df_Rohit_Y = df_Rohit['Good_Bad_Shot']
Avg_Ball_Speed=df_Rohit['Avg_Ball_Speed']
#Delivery_Number=df_Rohit['Delivery_Number']
dummy_bowler_type = pd.get_dummies(df_Rohit['Bowler_Type'])
dummy_home_away = pd.get_dummies(df_Rohit['Delivery_Length'])
dummy_line = pd.get_dummies(df_Rohit['Delivery_Line'])
dummy_length = pd.get_dummies(df_Rohit['Home_Away'])
dummy_shotype = pd.get_dummies(df_Rohit['Shot_Type'])
#dummy_line
df_Rohit_X = pd.concat([Avg_Ball_Speed,dummy_bowler_type,dummy_home_away,dummy_line,dummy_length,dummy_shotype],axis = 1)
df_Rohit_X.head()


Avg_Ball_Speed  left arm chinaman  left arm fast medium  left arm medium  \
0           139.2                  0                     0                0   
1           139.2                  0                     0                0   
2           138.3                  0                     0                0   
3           138.3                  0                     0                0   
4           138.3                  0                     0                0   

   left arm orthodox  right arm fast  right arm fast medium  \
0                  0               1                      0   
1                  0               1                      0   
2                  0               1                      0   
3                  0               1                      0   
4                  0               1                      0   

   right arm leg break  right arm medium  right arm off break   ...     \
0                    0                 0                    0   ...      
1                    0                 0                    0   ...      
2                    0                 0                    0   ...      
3                    0                 0                    0   ...      
4                    0                 0                    0   ...      

   Defensive_shot  Drive  Edge  Flick  Glance  Late_Cut  No_shot  Pull_hook  \
0               1      0     0      0       0         0        0          0   
1               0      0     1      0       0         0        0          0   
2               0      0     0      0       0         1        0          0   
3               0      0     0      0       0         0        0          1   
4               1      0     0      0       0         0        0          0   

   Sweep  Unknown  
0      0        0  
1      0        0  
2      0        0  
3      0        0  
4      0        0  

[5 rows x 31 columns]

In [131]:
x_train, x_test, y_train, y_test = train_test_split(df_Rohit_X, df_Rohit_Y, test_size=0.2,stratify=df_Rohit_Y, random_state=42)

In [132]:
tree_model2=tree.DecisionTreeClassifier(max_depth=4)
tree_model2.fit(x_train,y_train)
dt_shot_pred=tree_model2.predict(x_test)

In [133]:
print(accuracy_score(y_test,dt_shot_pred))

0.824601366743


In [134]:
print(confusion_matrix(y_test,dt_shot_pred))
print(classification_report(y_test,dt_shot_pred))

[[283  20]
 [ 57  79]]
             precision    recall  f1-score   support

        bad       0.83      0.93      0.88       303
       good       0.80      0.58      0.67       136

avg / total       0.82      0.82      0.82       439



# Hyper-parameter Tuning

In [203]:
from scipy.stats import randint #importing the random int function
from  sklearn.model_selection import RandomizedSearchCV #Using radomized search for hyperparmeter search
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score 

In [211]:
param_dist = {"max_depth": [5, None],
              "max_features": randint(1, 4),
              "min_samples_leaf": randint(1, 5),
              "criterion": ["gini", "entropy"]}

In [212]:
Decision_Tree_tunning = RandomizedSearchCV(tree_model2,param_dist,n_iter=10,cv=5) 
#Cv is cross validation generator
#param_dist is choosing distinct parameters

In [213]:
Decision_Tree_tunning.fit(x_train,y_train)

RandomizedSearchCV(cv=5, error_score='raise',
          estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best'),
          fit_params={}, iid=True, n_iter=10, n_jobs=1,
          param_distributions={'max_depth': [5, None], 'max_features': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000001A4191882E8>, 'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000001A419188630>, 'criterion': ['gini', 'entropy']},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          return_train_score=True, scoring=None, verbose=0)

In [214]:
y_pred = Decision_Tree_tunning.predict(x_test) #predicting on testing data

In [215]:
cm = confusion_matrix(y_test,y_pred)#creating the confusion matrix
cm

array([[265,  38],
       [ 39,  97]])

In [216]:
print(classification_report(y_test,y_pred)) #Printing the classification report

             precision    recall  f1-score   support

        bad       0.87      0.87      0.87       303
       good       0.72      0.71      0.72       136

avg / total       0.82      0.82      0.82       439



In [217]:
accuracy_score(y_test,y_pred)  #Checking the accuracy of our model

0.82460136674259676

In [218]:
print("Tuned Decision Tree Parameters: {}".format(Decision_Tree_tunning.best_params_))
#Printing out the parameters of the current search

Tuned Decision Tree Parameters: {'criterion': 'gini', 'max_depth': None, 'max_features': 3, 'min_samples_leaf': 2}


# After running the model 5 times the accuracy falls between 76% to 83%

# Model 3- Random Forest

In [235]:
from sklearn.ensemble import RandomForestClassifier
rf_model=RandomForestClassifier(criterion='gini',max_depth=5)
rf_model.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=5, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [236]:
rf_predd=rf_model.predict(x_test)

In [237]:
print(accuracy_score(y_test,rf_predd))

0.824601366743


In [238]:
print(confusion_matrix(y_test,rf_predd))
print(classification_report(y_test,rf_predd))

[[284  19]
 [ 58  78]]
             precision    recall  f1-score   support

        bad       0.83      0.94      0.88       303
       good       0.80      0.57      0.67       136

avg / total       0.82      0.82      0.82       439

