In [7]:
#Importing necessary libraries
import pandas as pd
import numpy as np

In [10]:
# Read the csv file and save it as a Pandas DataFrame
df_Warner = pd.read_csv("D:/knowledge/college docs/DSP/Project_1/New/Warner.csv")

In [11]:
df_Warner.head()

Unnamed: 0                                         Commentary Runs  \
0           0  Amir to Warner, <b>out</b> Bowled!! Amir has d...  NaN   
1           2  Amir to Warner, 1 run, short of a good length ...    1   
2           3  Hafeez to Warner, 1 run, flatter and on Warner...    1   
3           4  Hafeez to Warner, <b>FOUR</b>, Warner is off a...    4   
4           5  Amir to Warner, no run, this is even better! A...    0   

  Delivery_Length     Delivery_Line  Shot_Type Run/NoRun  \
0            Full  wicket_to_wicket      Flick     norun   
1           Short    outside_stumps    Unknown       run   
2      GoodLength  wicket_to_wicket    Unknown       run   
3         Unknown           Unknown  Pull_hook       run   
4            Full           Unknown      Drive     norun   

            Bowler_Type Bowler_Name  Avg_Ball_Speed ...   Beaten/NotBeaten  \
0  left arm fast medium        Amir           136.4 ...         not_beaten   
1  left arm fast medium        Amir           136.4 ...         not_beaten   
2   right arm off break      Hafeez            88.5 ...            Unknown   
3   right arm off break      Hafeez            88.5 ...         not_beaten   
4  left arm fast medium        Amir           136.4 ...         not_beaten   

  Home_Away Good_Bad_Shot  Opponent    Stadium  Shot_Zone Delivery_Number  \
0      home           bad  Pakistan  The Gabba  Midwicket              19   
1      home           bad  Pakistan  The Gabba      Cover              17   
2      home           bad  Pakistan  The Gabba    Unknown              16   
3      home          good  Pakistan  The Gabba  Midwicket              15   
4      home           bad  Pakistan  The Gabba    Unknown              14   

  Toss  TossDecision  D/N  
0    1       Batting   DN  
1    1       Batting   DN  
2    1       Batting   DN  
3    1       Batting   DN  
4    1       Batting   DN  

[5 rows x 22 columns]

In [12]:
null_columns=df_Warner.columns[df_Warner.isnull().any()]
null_columns

Index(['Runs', 'Dismissal_Type'], dtype='object')

In [13]:
df_Warner['Delivery_Length'].value_counts()

Short         766
Full          614
Unknown       491
GoodLength    484
FullToss       17
Name: Delivery_Length, dtype: int64

In [14]:
df_Warner['Delivery_Line'].value_counts()

outside_stumps      910
wicket_to_wicket    902
Unknown             560
Name: Delivery_Line, dtype: int64

In [15]:
df_Warner['Shot_Type'].value_counts()

Unknown           767
Drive             373
Defensive_shot    354
Pull_hook         294
Sweep             106
Cut               104
Edge              102
No_shot            95
Flick              81
Late_Cut           79
Glance             17
Name: Shot_Type, dtype: int64

In [16]:
df_Warner['Shot_Zone'].value_counts()

Unknown      882
Cover        413
Midwicket    220
Point        216
LongOff      187
SquareLeg    150
LongOn       133
ThirdMan     114
FineLeg       57
Name: Shot_Zone, dtype: int64

In [17]:
df_Warner['Bowler_Type'].value_counts()

left arm fast medium     484
right arm fast medium    443
right arm medium         360
right arm fast           314
right arm off break      291
left arm orthodox        279
right arm leg break      111
right arm offbreak        65
left arm chinaman         18
left arm medium            7
Name: Bowler_Type, dtype: int64

# Model 1-Decision Tree with multiple parameters

In [18]:
cols = ['Bowler_Type','Delivery_Length','Delivery_Line','Avg_Ball_Speed','Delivery_Number','Home_Away','Shot_Type']

df_Warner_Y = df_Warner['Good_Bad_Shot']
Avg_Ball_Speed=df_Warner['Avg_Ball_Speed']
Delivery_Number=df_Warner['Delivery_Number']
#line_df = rohit['Delivery Line'].to_frame
dummy_bowler_type = pd.get_dummies(df_Warner['Bowler_Type'])
dummy_home_away = pd.get_dummies(df_Warner['Delivery_Length'])
dummy_line = pd.get_dummies(df_Warner['Delivery_Line'])
dummy_length = pd.get_dummies(df_Warner['Home_Away'])
dummy_shotype = pd.get_dummies(df_Warner['Shot_Type'])
#dummy_line
df_Warner_X = pd.concat([Avg_Ball_Speed,Delivery_Number,dummy_bowler_type,dummy_home_away,dummy_line,dummy_length,dummy_shotype],axis = 1)
df_Warner_X.head()


Avg_Ball_Speed  Delivery_Number  left arm chinaman  left arm fast medium  \
0           136.4               19                  0                     1   
1           136.4               17                  0                     1   
2            88.5               16                  0                     0   
3            88.5               15                  0                     0   
4           136.4               14                  0                     1   

   left arm medium  left arm orthodox  right arm fast  right arm fast medium  \
0                0                  0               0                      0   
1                0                  0               0                      0   
2                0                  0               0                      0   
3                0                  0               0                      0   
4                0                  0               0                      0   

   right arm leg break  right arm medium   ...     Defensive_shot  Drive  \
0                    0                 0   ...                  0      0   
1                    0                 0   ...                  0      0   
2                    0                 0   ...                  0      0   
3                    0                 0   ...                  0      0   
4                    0                 0   ...                  0      1   

   Edge  Flick  Glance  Late_Cut  No_shot  Pull_hook  Sweep  Unknown  
0     0      1       0         0        0          0      0        0  
1     0      0       0         0        0          0      0        1  
2     0      0       0         0        0          0      0        1  
3     0      0       0         0        0          1      0        0  
4     0      0       0         0        0          0      0        0  

[5 rows x 33 columns]

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [21]:
x_train, x_test, y_train, y_test = train_test_split(df_Warner_X, df_Warner_Y, test_size=0.2,stratify=df_Warner_Y, random_state=42)

In [23]:
df_Warner_X.head()

Avg_Ball_Speed  Delivery_Number  left arm chinaman  left arm fast medium  \
0           136.4               19                  0                     1   
1           136.4               17                  0                     1   
2            88.5               16                  0                     0   
3            88.5               15                  0                     0   
4           136.4               14                  0                     1   

   left arm medium  left arm orthodox  right arm fast  right arm fast medium  \
0                0                  0               0                      0   
1                0                  0               0                      0   
2                0                  0               0                      0   
3                0                  0               0                      0   
4                0                  0               0                      0   

   right arm leg break  right arm medium   ...     Defensive_shot  Drive  \
0                    0                 0   ...                  0      0   
1                    0                 0   ...                  0      0   
2                    0                 0   ...                  0      0   
3                    0                 0   ...                  0      0   
4                    0                 0   ...                  0      1   

   Edge  Flick  Glance  Late_Cut  No_shot  Pull_hook  Sweep  Unknown  
0     0      1       0         0        0          0      0        0  
1     0      0       0         0        0          0      0        1  
2     0      0       0         0        0          0      0        1  
3     0      0       0         0        0          1      0        0  
4     0      0       0         0        0          0      0        0  

[5 rows x 33 columns]

In [24]:
from sklearn import tree

In [25]:
tree_model=tree.DecisionTreeClassifier(max_depth=4)
tree_model.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [26]:
dt_shot_pred=tree_model.predict(x_test)

In [27]:
print(accuracy_score(y_test,dt_shot_pred))

0.829473684211


In [28]:
print(confusion_matrix(y_test,dt_shot_pred))
print(classification_report(y_test,dt_shot_pred))

[[257  81]
 [  0 137]]
             precision    recall  f1-score   support

        bad       1.00      0.76      0.86       338
       good       0.63      1.00      0.77       137

avg / total       0.89      0.83      0.84       475



# Model 2- Decision Tree with limited parameters

In [47]:
df_Warner_Y = df_Warner['Good_Bad_Shot']
#Avg_Ball_Speed=df_Warner['Avg_Ball_Speed']
#Delivery_Number=df_Rohit['Delivery_Number']
dummy_bowler_type = pd.get_dummies(df_Warner['Bowler_Type'])
dummy_home_away = pd.get_dummies(df_Warner['Delivery_Length'])
dummy_line = pd.get_dummies(df_Warner['Delivery_Line'])
dummy_length = pd.get_dummies(df_Warner['Home_Away'])
dummy_shotype = pd.get_dummies(df_Warner['Shot_Type'])
#dummy_line
df_Warner_X = pd.concat([dummy_bowler_type,dummy_home_away,dummy_line,dummy_length,dummy_shotype],axis = 1)
df_Warner_X.head()


left arm chinaman  left arm fast medium  left arm medium  \
0                  0                     1                0   
1                  0                     1                0   
2                  0                     0                0   
3                  0                     0                0   
4                  0                     1                0   

   left arm orthodox  right arm fast  right arm fast medium  \
0                  0               0                      0   
1                  0               0                      0   
2                  0               0                      0   
3                  0               0                      0   
4                  0               0                      0   

   right arm leg break  right arm medium  right arm off break  \
0                    0                 0                    0   
1                    0                 0                    0   
2                    0                 0                    1   
3                    0                 0                    1   
4                    0                 0                    0   

   right arm offbreak   ...     Defensive_shot  Drive  Edge  Flick  Glance  \
0                   0   ...                  0      0     0      1       0   
1                   0   ...                  0      0     0      0       0   
2                   0   ...                  0      0     0      0       0   
3                   0   ...                  0      0     0      0       0   
4                   0   ...                  0      1     0      0       0   

   Late_Cut  No_shot  Pull_hook  Sweep  Unknown  
0         0        0          0      0        0  
1         0        0          0      0        1  
2         0        0          0      0        1  
3         0        0          1      0        0  
4         0        0          0      0        0  

[5 rows x 31 columns]

In [48]:
x_train, x_test, y_train, y_test = train_test_split(df_Warner_X, df_Warner_Y, test_size=0.2,stratify=df_Warner_Y, random_state=42)

In [49]:
tree_model2=tree.DecisionTreeClassifier(max_depth=4)
tree_model2.fit(x_train,y_train)
dt_shot_pred=tree_model2.predict(x_test)

In [50]:
print(accuracy_score(y_test,dt_shot_pred))

0.829473684211


In [51]:
print(confusion_matrix(y_test,dt_shot_pred))
print(classification_report(y_test,dt_shot_pred))

[[257  81]
 [  0 137]]
             precision    recall  f1-score   support

        bad       1.00      0.76      0.86       338
       good       0.63      1.00      0.77       137

avg / total       0.89      0.83      0.84       475



# Hyper-parameter Tuning

In [52]:
from scipy.stats import randint #importing the random int function
from  sklearn.model_selection import RandomizedSearchCV #Using radomized search for hyperparmeter search
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score 

In [87]:
param_dist = {"max_depth": [5, None],
              "max_features": randint(1, 4),
              "min_samples_leaf": randint(1, 9),
              "criterion": ["gini", "entropy"]}

In [88]:
Decision_Tree_tunning = RandomizedSearchCV(tree_model2,param_dist,n_iter=15,cv=8) 
#Cv is cross validation generator
#param_dist is choosing distinct parameters

In [89]:
Decision_Tree_tunning.fit(x_train,y_train)

RandomizedSearchCV(cv=8, error_score='raise',
          estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best'),
          fit_params={}, iid=True, n_iter=15, n_jobs=1,
          param_distributions={'max_depth': [5, None], 'max_features': <scipy.stats._distn_infrastructure.rv_frozen object at 0x00000233F4A6D7B8>, 'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_frozen object at 0x00000233F4A6D978>, 'criterion': ['gini', 'entropy']},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          return_train_score=True, scoring=None, verbose=0)

In [90]:
y_pred = Decision_Tree_tunning.predict(x_test) #predicting on testing data

In [91]:
cm = confusion_matrix(y_test,y_pred)#creating the confusion matrix
cm

array([[276,  62],
       [ 29, 108]])

In [92]:
print(classification_report(y_test,y_pred)) #Printing the classification report

             precision    recall  f1-score   support

        bad       0.90      0.82      0.86       338
       good       0.64      0.79      0.70       137

avg / total       0.83      0.81      0.81       475



In [93]:
accuracy_score(y_test,y_pred)  #Checking the accuracy of our model

0.80842105263157893

In [72]:
print("Tuned Decision Tree Parameters: {}".format(Decision_Tree_tunning.best_params_))
#Printing out the parameters of the current search

Tuned Decision Tree Parameters: {'criterion': 'entropy', 'max_depth': None, 'max_features': 2, 'min_samples_leaf': 1}


# Model 3- Random Forest

In [61]:
from sklearn.ensemble import RandomForestClassifier
rf_model=RandomForestClassifier(criterion='gini',max_depth=5)
rf_model.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=5, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [62]:
rf_predd=rf_model.predict(x_test)

In [63]:
print(accuracy_score(y_test,rf_predd))

0.818947368421


In [64]:
print(confusion_matrix(y_test,rf_predd))
print(classification_report(y_test,rf_predd))

[[303  35]
 [ 51  86]]
             precision    recall  f1-score   support

        bad       0.86      0.90      0.88       338
       good       0.71      0.63      0.67       137

avg / total       0.81      0.82      0.82       475

